### ISSUE TITLE
Telegram: Conversations

### ISSUE THREAD

**Issue by mrtn** [mpociot/botman#57] opened 2016-12-15 08:31 UTC
Hello,

I use botman in a new Laravel 5.3 application. I have tried with the laravel starter, but i couldnt get it to work. So i started with a clean install. 

As I am not very familiar with Laravel, I got it working, except the conversations. I have taken the Example conversations from the Laravel Starter.

When I use Start Conversation, the conversation is triggered and the buttons appear in Telegram. When I click a button, nothing happens. 

Can it be something with the cache? As i can read in previous issues and documentation, when used in Laravel, caching is automatic handled?

### Controller
```
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Mpociot\BotMan\BotManFactory;
use Mpociot\BotMan\BotMan;
use App\Conversations\ExampleConversation;

class BotManController extends Controller
{
	public function handle(Request $request)
	{
		$botman = app('botman');

		// Simple respond method
		$botman->hears('Hello|hi|Hi', function (BotMan $bot) {
			//Reply
			$bot->reply('Hi there :)');
		});

		$botman->hears('Start conversation', function (BotMan $bot) {
			$bot->startConversation(new ExampleConversation());
		});
		
		$botman->listen();
	}
}
```

### Conversation
```
namespace App\Conversations;

use Illuminate\Foundation\Inspiring;
use Mpociot\BotMan\Answer;
use Mpociot\BotMan\Button;
use Mpociot\BotMan\Conversation;
use Mpociot\BotMan\Question;

class ExampleConversation extends Conversation
{
    /**
     * First question
     */
    public function askReason()
    {
        $question = Question::create("Huh - you woke me up. What do you need?")
            ->fallback('Unable to ask question')
            ->callbackId('ask_reason')
            ->addButtons([
                Button::create('Tell a joke')->value('joke'),
                Button::create('Give me a fancy quote')->value('quote'),
            ]);
        return $this->ask($question, function (Answer $answer) {
            if ($answer->isInteractiveMessageReply()) {
                if ($answer->getValue() === 'joke') {
                    $joke = json_decode(file_get_contents('http://api.icndb.com/jokes/random'));
                    $this->say($joke->value->joke);
                } else {
                    $this->say(Inspiring::quote());
                }
            }
        });
    }

    /**
     * Start the conversation
     */
    public function run()
    {
        $this->askReason();
    }
}
```

**Comment by mpociot** [comment] 2016-12-15 08:34
Hi!

Have you added the `BotManServiceProvider` to your `config/app.php`? 
Also, can you tell me what the value of the `CACHE_DRIVER` environment variable in your `.env` file is?
It must be at least `file` - otherwise nothing will be cached and the conversations won't work.

**Comment by mrtn** [comment] 2016-12-15 08:43
Hi,

Thanks for the quick response.

- Yes, I have added the service provider and the alias in `config/app.php`.
- The `CACHE_DRIVER `in the .env file is FILE.

**Comment by mpociot** [comment] 2016-12-15 08:53
Is there anything in your `storage/logs/laravel.log` file?
Just tried it with your example code + Telegram without any issues.

**Comment by mrtn** [comment] 2016-12-15 09:01
There are no errors in the laravel.log file.

I've tried without buttons and simple text (like the pizza example in the readme) and I have the same issue.
After responding the bots' question, nothing happens. And no error is logged.

**Comment by mpociot** [comment] 2016-12-15 09:05
Can you and add a simple log function in your answer closure?
Like this:

```php
        return $this->ask($question, function (Answer $answer) {
            \Log::info(print_r($answer,true));
        });
```

Click a button and see if something got logged in the `laravel.log` file.

**Comment by mrtn** [comment] 2016-12-15 09:16
Nothing is logged :-(

**Comment by mpociot** [comment] 2016-12-15 10:29
Um okay..that's pretty weird.
Could you add this to your `handle` method to see if Telegram sends you the button click event?


```php
\Log::info(print_r($request->all(),true));
```

**Comment by mrtn** [comment] 2016-12-15 10:34
Tried and it does: `[data] => quote` when i clicked quote

**Comment by mpociot** [comment] 2016-12-15 10:38
Can you please post the complete log?
You can strip out the IDs if you want :)

**Comment by mrtn** [comment] 2016-12-15 10:42
Sure, here it is:

```
[2016-12-15 10:32:46] local.INFO: Array
(
    [update_id] => 888995600
    [callback_query] => Array
        (
            [id] => 54475400061572935
            [from] => Array
                (
                    [id] => 00000000
                    [first_name] => Maarten
                    [last_name] => Kumpen
                    [username] => Nickname
                )

            [message] => Array
                (
                    [message_id] => 616
                    [from] => Array
                        (
                            [id] => 55448565
                            [first_name] => MRTN
                            [username] => MRTN_bot
                        )

                    [chat] => Array
                        (
                            [id] => 0000000
                            [first_name] => Maarten
                            [last_name] => Lastname
                            [username] => Nickname
                            [type] => private
                        )

                    [date] => 1481797918
                    [text] => Huh - you woke me up. What do you need?
                )

            [chat_instance] => -60738844255598537752
            [data] => quote
        )

)
```

**Comment by mpociot** [comment] 2016-12-15 11:01
I don't really have a clue what could be wrong here - I still think this has to do with the cache.

Do you have additional services connected / configured?
Have you added the webhook to Telegram (I guess you have, because it gets called)?
Can you try a `php artisan cache:clear` in your bot directory, type `start conversation` and see if a cache file got created inside `storage/cache`?

**Comment by mrtn** [comment] 2016-12-15 11:13
A cache file is created when I type `start conversation`, when I push a button the file is deleted.

I have no other services configured. And indeed, I have configured the webhook, normal messages with replies works perfect. Only the conversations do not reply.

**Comment by mrtn** [comment] 2016-12-15 11:29
This is the content of the cache.

```
1481801785a:2:{s:12:"conversation";O:37:"App\Conversations\ExampleConversation":2:{s:6:"*bot";O:21:"Mpociot\BotMan\BotMan":6:{s:7:"payload";N;s:8:"*event";N;s:9:"*driver";O:37:"Mpociot\BotMan\Drivers\TelegramDriver":4:{s:10:"*payload";O:45:"Symfony\Component\HttpFoundation\ParameterBag":1:{s:13:"*parameters";a:2:{s:9:"update_id";i:882309609;s:7:"message";a:5:{s:10:"message_id";i:624;s:4:"from";a:4:{s:2:"id";i:12485636;s:10:"first_name";s:7:"Maarten";s:9:"last_name";s:6:"Kumpen";s:8:"username";s:9:"NickNme";}s:4:"chat";a:5:{s:2:"id";i:127805636;s:10:"first_name";s:7:"Maarten";s:9:"last_name";s:6:"Kumpen";s:8:"username";s:9:"NickNme";s:4:"type";s:7:"private";}s:4:"date";i:1481799985;s:4:"text";s:18:"Start conversation";}}}s:8:"*event";O:29:"Illuminate\Support\Collection":1:{s:8:"*items";a:5:{s:10:"message_id";i:624;s:4:"from";a:4:{s:2:"id";i:12485636;s:10:"first_name";s:7:"Maarten";s:9:"last_name";s:6:"Kumpen";s:8:"username";s:9:"NickNme";}s:4:"chat";a:5:{s:2:"id";i:12485636;s:10:"first_name";s:7:"Maarten";s:9:"last_name";s:6:"Kumpen";s:8:"username";s:9:"NickNme";s:4:"type";s:7:"private";}s:4:"date";i:14899944785;s:4:"text";s:18:"Start conversation";}}s:7:"*http";O:24:"Mpociot\BotMan\Http\Curl":0:{}s:9:"*config";O:29:"Illuminate\Support\Collection":1:{s:8:"*items";a:1:{s:14:"telegram_token";s:45:"266242179:AAGgjj3dTqHn41hB1VvOvO30xtHHdmI2gdI";}}}s:10:"*message";O:22:"Mpociot\BotMan\Message":5:{s:10:"*message";s:18:"Start conversation";s:7:"*user";i:14899944785;s:10:"*channel";i:12485636;s:10:"*payload";r:25;s:9:"*extras";a:0:{}}s:28:"Mpociot\BotMan\BotMancache";O:33:"Mpociot\BotMan\Cache\LaravelCache":0:{}s:10:"*matches";a:0:{}}s:8:"*token";N;}s:4:"next";s:228:"C:32:"Opis\Closure\SerializableClosure":182:{a:5:{s:3:"use";N;s:8:"function";s:100:"function (\Mpociot\BotMan\Answer $answer) {
            \Log::info(print_r($answer,true));
        }";s:5:"scope";N;s:4:"this";N;s:4:"self";N;}}";}
```

**Comment by mpociot** [comment] 2016-12-15 16:23
Ah..just had another idea.
What's the route you use for your bot logic?

Please make sure to add it to your `VerifyCsrfToken` middleware!
See: https://github.com/mpociot/botman-laravel-starter/blob/master/app/Http/Middleware/VerifyCsrfToken.php#L14-L17

**Comment by mrtn** [comment] 2016-12-15 17:24
I had botman, and i ve added botman/*, but I still don't get a response.

**Comment by mrtn** [comment] 2016-12-15 17:35
The only thing I can tell extra, at the moment, is, when I click one of the buttons a second time in the chat screen, they disappear from the screen. But no logging is added.

Meanwhile I ve tried the logging, as requested earlier, but its still the same.

**Comment by mrtn** [comment] 2016-12-15 18:55
I need to dig in the code why the conversation is not triggered when an anser is sent. As we said, probably its the caching. 

For me it takes some time as i m not very familiar with Laravel (codeigniter dev before the switch to Laravel).

If you have ideas about this issue, let me know I ll provide as much info as I can.

I've written down all my own steps, I want to post a step by step tutorial on my website.

**Comment by jeroengerits** [comment] 2016-12-15 23:43
How does your hosting env. look like? Can you tell a bit more about that? Where is your ssl from for example?

**Comment by mrtn** [comment] 2016-12-25 13:48
Cant get it to work.
Tried clean installs, the laravel starter, same issue with conversations every try.

**Comment by mpociot** [comment] 2016-12-25 14:05
I really have no idea. It must be some kind of issue on your side. 
Have you tried it on a server other than your local development one?

**Comment by jfern01** [comment] 2016-12-27 17:06
Can confirm this issue happens on a vanilla install of Laravel 5.3.

**Comment by mpociot** [comment] 2016-12-27 19:30
Have you also tried it on a host other than your local environment? I checked this a few days ago using both, the BotMan Laravel starter project as well as a standalone implementation and it worked without any flaws.

**Comment by jfern01** [comment] 2016-12-27 19:37
I'm currently trying out BotMan on a remote development server. The webhook receives the user's answer but the callback doesn't get executed. Laravel is not logging any errors either.

**Comment by mrtn** [comment] 2016-12-28 07:07
I have the issue also on shared hosting with cPanel. So not only dev env.

**Comment by mpociot** [comment] 2016-12-28 09:14
Just trying to guess what could be wrong here...

Which PHP version do you use? And is there any other place for PHP error logs?

**Comment by jfern01** [comment] 2016-12-29 18:05
The problem lies in `$next = unserialize($convo['next']);`, line 342 in Mpociot\BotMan\BotMan. The unserialization fails for some reason and the callback never gets executed.

**Comment by mrtn** [comment] 2016-12-30 08:49
@mpociot The PHP version is 5.6

**Comment by jfern01** [comment] 2016-12-30 19:31
Same here, PHP 5.6.

**Comment by mpociot** [comment] 2016-12-30 22:29
Can you try it again with the latest `dev-master` version?
I'm unable to reproduce this issue and all tests on Travis also pass using 5.6.

@jfern01 if you still encounter this issue - can you please post the content of one of your botman cache files?
It seems like the closure scope is not correctly serialized.

**Comment by mrtn** [comment] 2016-12-31 08:44
I have tried with the latest `dev-master` and i ve performed a composer update, and the issue is the same. :-(

The cache is created, when the conversation is started. And when you respons on the question, the cache is removed.

**Comment by SergiX44** [comment] 2017-01-08 21:04
Same issue here with Laravel 5.3, there is my code:
```
class BotManController extends Controller {

	protected $bot;

	public function __invoke($id) {
		$selected_bot= Bot::findOrFail($id);

		$config = [
			'telegram_token' => $selected_bot->telegram_token
		];

		$this->bot = BotManFactory::create($config, new LaravelCache());
		$this->register_commands();
		$this->bot->listen();
	}

	protected function register_commands() {
		$this->bot->hears('/start', function (Botman $bot) {
			$bot->reply('Hello yourself.');
		});

		$this->bot->hears('/pizza', function (Botman $bot) {
			$bot->startConversation(new PizzaConversation());
		});
	}
}
```

i'm not using the Botmanserviceprovider, because i need to manage more bots (#56). The PizzaConversation it's the same as the readme example. The bot is replying to the /start, but not to /pizza command.
PHP 7.0.6, Laravel 5.3.

**Comment by gromez** [comment] 2017-01-21 23:03
I'm not using Laravel (I'm using Slim) but I have a similar issue, I can start the conversation, but no way to answer.

> Serialization of 'Closure' is not allowed

Tried with `dev-master` but same problem.

**Comment by mpociot** [comment] 2017-01-22 00:01
@gromez can you tell me which cache driver you use and how your conversation code looks like?

Since BotMan serializes the callback Closure to pick it up later, errors can occur if your callback Closure contains a Closure itself.

**Comment by gromez** [comment] 2017-01-22 06:46
@mpociot sure, here is the code I'm using

```
$cache = new \Symfony\Component\Cache\Adapter\FilesystemAdapter();
$botman = \Mpociot\BotMan\BotManFactory::create($settings, new \Mpociot\BotMan\Cache\SymfonyCache($cache));

$botman->hears('/pizza', function (BotMan $bot) {
    $bot->startConversation(new PizzaConversation);
});

$botman->listen();
```

I'm using the exactly same PizzaConversation class as in your example.

First problem (related to the Symfony cache) : `Cache key "conversation:279775023-279775023" contains reserved characters {}()/\@:`
If I replace the `:` with `-` it's OK.

Second problem : `opis/closure` throws `Serialization of 'Closure' is not allowed`

Thanks for your work!

**Comment by mpociot** [comment] 2017-01-22 07:38
Please create a separate issue for this as this is not related to Telegram but to the Symfony Cache. Otherwise I can't keep track of this. 

Thank you.

**Comment by mpociot** [comment] 2017-02-14 22:05
I'm closing this issue. Please reopen either this one or a new issue if the problem still occurs for you and you know the steps to reproduce it.

**Closed by mpociot** 2017-02-14 22:05 UTC

**Comment by theemfs** [comment] 2017-09-09 05:23
I have a same problem.
L 5.5.2
php 7.0
botman 2

replies working, but in conversations only first question fired.
Replies on this question handled as a new message to bot.

![image](https://user-images.githubusercontent.com/1768403/30237306-e807f274-9561-11e7-9602-c18a72042a7f.png)

**Comment by mpociot** [comment] 2017-09-09 06:02
Do you see anything in your Laravel log?

**Comment by theemfs** [comment] 2017-09-09 06:48
in log I see only received message (request)
Log::info($request->all());

**Comment by theemfs** [comment] 2017-09-09 06:52
I think it's better to update 
"Basic Usage without BotMan Studio" paragraph:

```
// create an instance
$botman = BotManFactory::create($config);
```

change to

```
use BotMan\BotMan\Cache\LaravelCache;

// create an instance
$botman = BotManFactory::create($config, new LaravelCache());
```

**Comment by mpociot** [comment] 2017-09-09 06:54
Ah so you got it working?
I thought you use the BotMan studio. 

Yeah I have that mentioned after the get started example, because it depends which framework you use.

**Comment by mpociot** [comment] 2017-09-09 06:55
I’ll make sure to add a link to https://botman.io/2.0/cache-drivers after the basic usage example.

**Comment by iDuke** [comment] 2018-01-02 05:19
Still have this issue.

**Comment by elephantux** [comment] 2018-02-27 22:51
Laravel 5.6
BotMan 2 (not Studio)
PHP 7.1
CACHE_DRIVER=file

Same issue. @theemfs solution work for me:
```
use BotMan\BotMan\Cache\LaravelCache;

// create an instance
$botman = BotManFactory::create($config, new LaravelCache());
```

**Comment by max-kovpak** [comment] 2018-11-13 10:38
I had the same problem.
I use botman with Symfony and the problem was with loading drivers. For laravel it works perfect cos all drivers were loaded in the Service Provider but for the symfony you have to load all drivers himself.
I followed the docs and load just TelegramDriver but when a user sends images nothing happens, cos TelegramPhotoDriver was not loaded.

**Comment by laskarazhar-hiveup** [comment] 2019-09-16 09:14
If you are using BotMan with Laravel without BotMan Studio : 

You can simply use `$botman = BotManFactory::create($config, new LaravelCache());` to enable caching for Conversations.

Thanks to @theemfs :1st_place_medal:
