### ISSUE TITLE
Laravel 5.3/5.4 turns into an infinite loop

### ISSUE THREAD

**Issue by sbasi5576** [mpociot/botman#176] opened 2017-01-30 05:17 UTC
regardless of what or whether I type or not, I start seeing 'I can be better.' message repeatedly.  And there is no way to disable it without removing the route.  This happens with the laravel example app as well.

use Mpociot\BotMan\BotMan;
Route::any('/botman', function() {
$botman = app('botman');
$botman->hears('hello', function (BotMan $bot) {
    $bot->reply('I can be better.');
});
$botman->listen();
});

**Comment by mpociot** [comment] 2017-01-30 05:43
You should probably see something in your error log. 
Also, which driver are you using?

**Comment by sbasi5576** [comment] 2017-01-30 05:51
I am not seeing anything in my logs.  I am seeing this in facebook messenger.  I am not making any driver  specific calls.  I initially started with the example implementation that you have.  Had the same issue and I was never able to Start Conversation.  Then I thought that may be I should follow your step by step instructions on the official site and github page.  Implemented all the steps.  The bot works except that return the reply regardless.  If I try using $botman->hears it still stays at the first reply.

**Comment by mpociot** [comment] 2017-01-30 06:29
Okay... I think I need some more information from you. 

How do you share the URL with Facebook? If it's using valet, what is the response code that Facebook receives?

Please also try the 'dev-master' branch of BotMan, even though that shouldn't be a problem.

**Comment by sbasi5576** [comment] 2017-01-30 07:41
For some reason the webhook was not working and trying to change it I saw the following error:
The URL couldn't be validated. Response does not match challenge, expected value="173482194", received=""

This was causing the infinite loop to kick.  But then I  added 
$botman->verifyServices(env('TOKEN_VERIFY'));

right under the $botman = app('botman');

The webhook eorros got resolved but The messages stopped working at all. I tried moving all the code to a Contorller to see if that will resolve the issue, but unfortunately no.  Final code in the routes/web.php is as follows: 

<?php

use Mpociot\BotMan\BotMan;
Route::any('/botman', function() {

$botman = app('botman');
$botman->verifyServices(env('TOKEN_VERIFY'));

$botman->hears('hello', function (BotMan $bot) {

$bot->reply('does it work now?');
});

$botman->listen();
});

And yes, I have the TOKEN_VERIFY in my .env file.

**Comment by mpociot** [comment] 2017-01-30 13:10
Have you successfully validated the webhook on Facebooks end?
Facebook has some kind of protection, that kicks in if the webhook was unreachable for a certain number of times. Maybe that's happening for you.

**Comment by sbasi5576** [comment] 2017-01-30 16:14
Yes, I have been able to validate the webhook on facebook end. Despite the validation it won't work.  Unless, Laravel has some issue based on my knowledge the route  should work as designed.

**Comment by sbasi5576** [comment] 2017-01-31 08:23
Marcel - looking at your configuration documentation - it points to 
$botman->verifyServices('MY_SECRET_VERIFICATION_TOKEN');

Is MY_SECRET_VERIFICATION_TOKEN the TOKEN_VERIFY we use to validate our webhook with facebook?  We do not set a variable MY_SECRET_VERIFICATION_TOKEN anywhere.  Where does this value come from?  I tried using my own token_verify value as well But no success.

**Comment by mpociot** [comment] 2017-01-31 08:26
When you add / edit the webhook on developer.facebook.com you have to provide a unique verification key. That's the `MY_SECRET_VERIFICATION_TOKEN` value.
Facebook will then send a test request to your webhook endpoint and will try to validate the tokens. That's what the `verifyServices` method is doing.

If you can successfully add the webhook to Facebook, the verification process is finished.

**Comment by sbasi5576** [comment] 2017-01-31 08:32
Thanks.  Yes, that is exactly what I did.  And this toke should be in the single quotes i.e. 'sbasi_secret_token' 

Full code looks like this - $botman->verifyServices('sbasi_secret_token');
Correct?

**Comment by mpociot** [comment] 2017-01-31 08:47
Yes, that's correct.

If I understood you correctly, you had no problem adding the webhook to Facebook, right?
Then you have already verified the URL.

**Comment by sbasi5576** [comment] 2017-01-31 08:52
Yes, there is no problem adding the webhook.    And the following code from from the botman.php route executes fine - 

$botman->hears('test', function($bot){
  $bot->reply('hello!');

But after that it goes into an infinte loop and keeps on sending hello!.  Also, we don't use 
$botman->verifyServices('sbasi_secret_token'); in the botman.php route.  Could that be a problem?  the verifyServices is used only when the BotManController is intialized.

**Comment by mpociot** [comment] 2017-02-05 21:39
Can you tell me for which Facebook events you subscribed the webhook? 
Try again with these only:
`messages, messaging_account_linking, messaging_optins, messaging_postbacks`

**Comment by mpociot** [comment] 2017-02-14 22:04
I'm closing this issue, as I am unable to reproduce it. Let me know if this still occurs and what the steps are to reproduce it.

**Closed by mpociot** 2017-02-14 22:04 UTC
